# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import connector_pb2 as connector__pb2


class ConnectorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetData = channel.unary_stream(
        '/qlik.connect.Connector/GetData',
        request_serializer=connector__pb2.DataRequest.SerializeToString,
        response_deserializer=connector__pb2.DataChunk.FromString,
        )
    self.GetMetaInfo = channel.unary_unary(
        '/qlik.connect.Connector/GetMetaInfo',
        request_serializer=connector__pb2.MetaInfoRequest.SerializeToString,
        response_deserializer=connector__pb2.MetaInfo.FromString,
        )


class ConnectorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetData(self, request, context):
    """* The standard way to send data.
    First send GetDataResponse as initial meta data.
    Then send DataChunk stream.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMetaInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ConnectorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetData': grpc.unary_stream_rpc_method_handler(
          servicer.GetData,
          request_deserializer=connector__pb2.DataRequest.FromString,
          response_serializer=connector__pb2.DataChunk.SerializeToString,
      ),
      'GetMetaInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetMetaInfo,
          request_deserializer=connector__pb2.MetaInfoRequest.FromString,
          response_serializer=connector__pb2.MetaInfo.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'qlik.connect.Connector', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
